spring:
  profiles:
    active: local
  data:
    rest:
      default-page-size: 30
      limit-param-name: limit
      max-page-size: 30
      page-param-name: offset
  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

---
spring:
  profiles: local
  datasource:
    platform: h2
    url: jdbc:h2:~/h2/employee-management

---
spring:
  profiles: test
  datasource:
    platform: h2
    generate-unique-name: true
